project_id = "iizsoqdzhwrpddsineug"

[functions.verify-ots-proof]
verify_jwt = false

[functions.verify-timestamp]
verify_jwt = false

[functions.process-registro]
verify_jwt = false

[functions.timestamp-free]
verify_jwt = false
